/* eslint-disable @next/next/no-head-element */
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>My Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={styles.container}>
      <nav className={styles.navigation_bar}>
            <Link className={styles.links} href="/">
              Home
            </Link>
            <Link className={styles.links} href="/diary">
              Diary
            </Link>
          </nav>
          {children}</body>
    </html>
  );
}
